const vm=require('vm'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const intervals=new Map(),raf=new Map(),storage=new Map();let counter=0,doc;
class Element{
 constructor(selector=''){this.selector=selector;this.children=[];this.nodes=new Map();this.events=new Map();this.style={setProperty(){}};this.dataset={};this.width=selector.includes('tetris')?200:640;this.height=selector.includes('tetris')?400:360;this.value='';this.textContent='';this.innerHTML='';this.hidden=false;const set=new Set(selector==='#desktop'?['hidden']:[]);this.classList={contains:n=>set.has(n),add:(...a)=>a.forEach(n=>set.add(n)),remove:(...a)=>a.forEach(n=>set.delete(n)),toggle:n=>set.has(n)?set.delete(n):set.add(n)};}
 querySelector(s){if(!this.nodes.has(s))this.nodes.set(s,new Element(s));return this.nodes.get(s);}querySelectorAll(){return [];}appendChild(el){this.children.push(el);return el;}append(el){this.children.push(el);}remove(){}closest(){return this;}contains(el){return el===this||[...this.nodes.values()].includes(el);}focus(){doc.activeElement=this;}addEventListener(e,f){if(!this.events.has(e))this.events.set(e,[]);this.events.get(e).push(f);}removeEventListener(e,f){this.events.set(e,(this.events.get(e)||[]).filter(x=>x!==f));}dispatchEvent(e){for(const fn of this.events.get(e.type)||[])fn(e);}click(){this.dispatchEvent({type:'click',preventDefault(){}});this.onclick?.();}getContext(){return new Proxy({createLinearGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>(o[k]=v,true)});}setAttribute(){}setPointerCapture(){}
}
doc=new Element();doc.documentElement=new Element();doc.body=new Element();doc.createElement=()=>new Element();doc.hidden=false;
const context={document:doc,console,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v))},matchMedia:()=>({matches:false}),navigator:{language:'es',userAgent:'Test'},screen:{width:1440,height:900},innerWidth:1440,innerHeight:900,performance:{now:()=>1000},setTimeout:()=>++counter,clearTimeout(){},setInterval:f=>{const id=++counter;intervals.set(id,f);return id;},clearInterval:id=>intervals.delete(id),requestAnimationFrame:f=>{const id=++counter;raf.set(id,f);return id;},cancelAnimationFrame:id=>raf.delete(id),MutationObserver:class{observe(){}disconnect(){}},KeyboardEvent:class{constructor(type,data){Object.assign(this,{type,preventDefault(){}},data);}},addEventListener(){},removeEventListener(){},location:{reload(){}},Date,Math,Promise};context.window=context;vm.createContext(context);
let core=fs.readFileSync(path.join(root,'script.js'),'utf8').replace('reset();draw();drawNext();','window.__tetris={start,hardDrop,rotate,collide,tick,togglePause,get:()=>({board,piece,score,lines,level,running,paused}),setBoard:v=>board=v};reset();draw();drawNext();').replace(/buildLevel\(\);draw\(\);\r?\n   }},/,'window.__pac={start,step,eat,collision,chooseGhost,togglePause,get:()=>({map,dots,powers,player,ghosts,score,lives,level,running,paused,tickNo}),clear:()=>{dots.clear();powers.clear();},setTick:n=>tickNo=n};buildLevel();draw();\n   }},');
let upgrade=fs.readFileSync(path.join(root,'upgrade.js'),'utf8').replace('loadLevel();hud();raf=requestAnimationFrame(loop);','window.__doom={start,tick,fire,render,pause,get:()=>({player,hp,ammo,enemies,items,level,score,running,paused,won}),set:(h,a)=>{hp=h;ammo=a;}};loadLevel();hud();raf=requestAnimationFrame(loop);');upgrade=upgrade.slice(0,upgrade.lastIndexOf('buildIcons();buildMenu();buildClock();'));
vm.runInContext(core,context);vm.runInContext(upgrade,context);
const run=s=>vm.runInContext(s,context);const bind=id=>{const body=new Element('body'),win=new Element('win');context.testBody=body;context.testWin=win;run(`Apps.${id}.bind(testBody,testWin)`);return {body,win};};
const tests=[];function pass(label){tests.push(label);}
const t=bind('tetris');context.__tetris.start();let g=context.__tetris.get();assert(g.running);let ids=new Set();for(let i=0;i<7;i++){ids.add(context.__tetris.get().piece.id);context.__tetris.hardDrop();}assert.equal(ids.size,7);pass('Tetris: bag contains all seven pieces');
for(let repeat=0;repeat<3;repeat++){g=context.__tetris.get();g.piece.shape=[[1],[1],[1],[1]];g.piece.x=0;g.piece.y=0;const b=Array.from({length:20},()=>Array(10).fill(null));for(let y=16;y<20;y++)for(let x=1;x<10;x++)b[y][x]='#fff';context.__tetris.setBoard(b);context.__tetris.hardDrop();}
g=context.__tetris.get();assert.equal(g.lines,12);assert.equal(g.level,2);assert(g.score>=2400);context.__tetris.togglePause();const py=g.piece.y;context.__tetris.tick();assert.equal(context.__tetris.get().piece.y,py);pass('Tetris: line clears, level 2, paused time');context.__tetris.togglePause();doc.activeElement=doc.body;doc.dispatchEvent({type:'focusin'});assert(context.__tetris.get().paused);pass('Window lifecycle: changing focus pauses the game');t.win.__cleanup();assert.equal(intervals.size,0);
const p=bind('pacman');context.__pac.start();g=context.__pac.get();function reachable(map,x,y,tunnel=false){const seen=new Set(),q=[[x,y]];while(q.length){const [x,y]=q.shift(),key=`${x},${y}`;if(seen.has(key)||map[y]?.[x]==='#'||map[y]?.[x]===undefined)continue;seen.add(key);for(let [nx,ny] of [[x+1,y],[x-1,y],[x,y+1],[x,y-1]]){if(tunnel&&ny===7)nx=(nx+19)%19;if(nx>=0&&nx<map[0].length)q.push([nx,ny]);}}return seen;}
const reach=reachable(g.map,g.player.x,g.player.y,true);assert([...g.dots,...g.powers].every(k=>reach.has(k)));pass('Pac-Man: every pellet and power pellet reachable');
context.__pac.clear();context.__pac.eat();assert.equal(context.__pac.get().level,2);g=context.__pac.get();context.__pac.setTick(15);g.ghosts[0].x=g.player.x;g.ghosts[0].y=g.player.y;context.__pac.collision();assert.equal(context.__pac.get().lives,2);context.__pac.collision();assert.equal(context.__pac.get().lives,2);pass('Pac-Man: level progression, life loss and respawn protection');context.__pac.togglePause();let tick=context.__pac.get().tickNo;context.__pac.step();assert.equal(context.__pac.get().tickNo,tick);p.win.__cleanup();assert.equal(intervals.size,0);
const d=bind('doom');context.__doom.start();g=context.__doom.get();g.player.a=0;context.__doom.fire();assert.equal(context.__doom.get().ammo,23);assert.equal(g.enemies[0].hp,1);context.__doom.fire();assert.equal(context.__doom.get().ammo,23);pass('Sector 13: hitscan, ammunition, fire cooldown');
const maps=run('SECTOR_MAPS');for(const map of maps){assert.equal(reachable(map,1,1).size,map.join('').split('.').length-1);}pass('Sector 13: all three maps fully connected');
for(let i=0;i<3;i++){g=context.__doom.get();g.enemies.forEach(e=>e.hp=0);g.player.x=10.5;g.player.y=8.5;context.__doom.tick(.01);context.__doom.render();}assert(context.__doom.get().won);assert(!context.__doom.get().running);pass('Sector 13: three-sector victory');context.__doom.start();context.__doom.set(1,0);g=context.__doom.get();g.enemies[0].x=g.player.x;g.enemies[0].y=g.player.y;g.enemies[0].attack=0;context.__doom.tick(.1);assert.equal(context.__doom.get().hp,0);assert(!context.__doom.get().running);pass('Sector 13: death stops campaign');d.win.__cleanup();assert.equal(raf.size,0);assert.equal(intervals.size,0);pass('Closing games releases every timer and animation');
const v=bind('easter');for(const answer of ['42','konami','josemi']){v.body.querySelector('#vault-answer').value=answer;v.body.querySelector('.vault-form').dispatchEvent({type:'submit',preventDefault(){}});}assert.equal(storage.get('josemi-vault'),'3');assert(v.body.querySelector('.vault-form').hidden);pass('Vault: three keys unlock and persist');
context.output=[];context.print=s=>context.output.push(s);run(`runCommand('echo <img src=x onerror=alert(1)>',print,()=>{})`);assert(context.output[0].includes('&lt;img'));pass('Terminal: user text is escaped');
const css=fs.readFileSync(path.join(root,'style.css'),'utf8');assert.equal((css.match(/\{/g)||[]).length,(css.match(/\}/g)||[]).length);assert(!fs.readFileSync(path.join(root,'index.html'),'utf8').includes('id="cursor"'));pass('CSS braces balanced; cursor removed');console.log(JSON.stringify({result:'PASS',tests},null,2));
